# Infos du projet (depuis SonarCloud)
sonar.projectKey=mohamedkhelil_first-laravel-project
sonar.organization=mohamedkhelil
sonar.projectName=Laravel Todo App
sonar.projectVersion=1.0

# Dossiers à analyser
sonar.sources=app,routes,database
sonar.tests=tests

# Langage
sonar.language=php

# Rapport de couverture PHPUnit
sonar.php.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**

# Encodage
sonar.sourceEncoding=UTF-8

# URL SonarCloud
sonar.host.url=https://sonarcloud.io

# Token d'authentification
sonar.token=471eef16b436bfb1c2a01f42034e33d5fccb2c50
